version: "3.3"

services:

  clip:
      build:
        context: service
      environment:
        - PRODUCTS_DATASET_URL=google_drive_folder_url
        - DATASET_PATH=data/dataset
        - OUTPUT_FOLDER=data/model
        - REPO_ID=openai/clip-vit-large-patch14-336
        - OUT_JSON=data/src.json
        - NUM_TRAIN_EPOCHS=3
        - BATCH_SIZE=32
        - NVIDIA_VISIBLE_DEVICES=all
      volumes:
        - "./data:/app/data"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [ gpu ]